### PR TITLE
Fix website lint

### PR DESCRIPTION
**Pull request by ghost**
Contributes to #48 and adds to #61

## What did you do?
Fix lint configuration and all lint errors.

## Why did you do it?
Discussed in issue #48

## How have you tested it?
Locally

## Were docs updated if needed?

- [ ] No
- [ ] Yes
- [X] N/A

#### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new console logs
- [X] Fixes entire issue
- [ ] Partial fix for issue

### CODE REVIEW

**Comment by arianahl** [comment]
There are 23 leftover **warnings** which I didn't know how to fix exactly:

```

/Users/arianahl/git/FairChange/website/components/common/MainContentArea.tsx
  59:66  warning  Unexpected console statement  no-console

/Users/arianahl/git/FairChange/website/components/common/MapUtils.ts
  22:59  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any
  68:28  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/arianahl/git/FairChange/website/components/common/types.ts
  20:26  warning  Unexpected any. Specify a different type  @typescript-eslint/no-explicit-any

/Users/arianahl/git/FairChange/website/components/pages/IncidentMap.tsx
  7:28  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/arianahl/git/FairChange/website/context/MapContext.tsx
   68:9   warning  Unexpected any. Specify a different type                                             @typescript-eslint/no-explicit-any
   69:33  warning  Unexpected any. Specify a different type                                             @typescript-eslint/no-explicit-any
  117:9   warning  Forbidden non-null assertion                                                         @typescript-eslint/no-non-null-assertion
  162:15  warning  Refactor this function to reduce its Cognitive Complexity from 23 to the 15 allowed  sonarjs/cognitive-complexity
  218:24  warning  Forbidden non-null assertion                                                         @typescript-eslint/no-non-null-assertion
  218:24  warning  Forbidden non-null assertion                                                         @typescript-eslint/no-non-null-assertion

/Users/arianahl/git/FairChange/website/hooks/useMapData.ts
  5:27  warning  Missing return type on function  @typescript-eslint/explicit-module-boundary-types

/Users/arianahl/git/FairChange/website/js/script.js
   94:52  warning  No magic number: 6                                                                   no-magic-numbers
  111:11  warning  Refactor this function to reduce its Cognitive Complexity from 21 to the 15 allowed  sonarjs/cognitive-complexity
  139:17  warning  Remove the unnecessary boolean literal                                               sonarjs/no-redundant-boolean
  141:16  warning  Remove the unnecessary boolean literal                                               sonarjs/no-redundant-boolean
  153:25  warning  Remove the unnecessary boolean literal                                               sonarjs/no-redundant-boolean
  155:16  warning  Remove the unnecessary boolean literal                                               sonarjs/no-redundant-boolean
  169:17  warning  Remove the unnecessary boolean literal                                               sonarjs/no-redundant-boolean
  207:20  warning  No magic number: 6                                                                   no-magic-numbers
  215:44  warning  No magic number: 6                                                                   no-magic-numbers
  231:6   warning  No magic number: 1500                                                                no-magic-numbers
  240:3   warning  Unexpected console statement                                                         no-console

✖ 23 problems (0 errors, 23 warnings)
```

**Comment by upkarlidder** [comment]
I believe @ikhnaton is taking a look. Thank you for your patience @arianahl.

**Comment by demilolu** [comment]
@arianahl  Thanks for your contribution! would you be available to join us on October 29th for our Demo Day? - https://www.crowdcast.io/e/hacktoberfest-demo-day/register. 
We'd also love for you to demo/walk us through one of your PRs during this session if you can. Pls let me know if you're interested :)

**Comment by ghost** [comment]
@demilolu thank you for the invitation. Sadly I'm off that day and won't be able to attend. It has been great learning about the projects and being able to contribute. Good luck!

**Pull request closed without merging**
